### ISSUE TITLE
Max number of tabs

### ISSUE THREAD

**Issue by paulinder** [picnicss/picnic#101]
Hi,

Really like the library.

I just spent a couple of hours trying to make a page with a 5-tab element, using the code samples in your documentation. After finally going to look through the Picnic source for the tabs class, I found that there is a maximum of [4 tabs](https://github.com/picnicss/picnic/blob/master/src/plugins/tabs/_class.scss#L87) provided through this library. 

So, I suppose a solution to this issue would be to decide whether higher number tabs should be possible - or, perhaps, a note should be added to the documentation.

Thank you,

Paul

**Comment by franciscop** [comment]
Please see https://github.com/picnicss/picnic/issues/113, tabs are going out in the next version since they are a super hacky solution that *should* be full of bugs.
