### ISSUE TITLE
Responsive Menu doesn't scroll

### ISSUE THREAD

**Issue by toddgibson** [picnicss/picnic#108]
Hello,

If there are more links in the responsive slide-out menu than height available the menu will not scroll.  I am using code very similar to the documentation, but with more links.

![image](https://cloud.githubusercontent.com/assets/3081793/17030299/e64c8d6c-4f3c-11e6-8fdb-9b83a79b1c26.png)

**Comment by franciscop** [comment]
Thank you for reporting thins, I could reproduce this [as can be seen here](https://jsfiddle.net/q7L0j1p4) and I fixed it [as can be seen here](https://jsfiddle.net/q7L0j1p4/1/).
