### ISSUE TITLE
Checkbox without text

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#114]
Report from Email:

For my current side-project i chose Picnic as CSS framework. I read on hackernews that you always try to improve picnic, so heres something that in most cases its not necessary to have a checkbox without text, but in my case it would make sense (see image):

![demo](https://cloud.githubusercontent.com/assets/2801252/17936480/e929d0a2-6a59-11e6-9f25-352f324d7b93.png)

The checkbox disappears if I don't have a label for it. When I just don't put any text in the label, there still exists some space. I sure find a little hack for it, but this 'problem' still exists.

**Comment by NetLancer** [comment]
I don't know the solution but maybe it worth adding some JS workaround for this thing?
Picnic's real nice framework - my thanx too !

**Comment by franciscop** [comment]
This problem comes from #123 , the `<td>` have a *big* padding-right (see reasoning in that issue) not from the checkbox itself.
