### ISSUE TITLE
Mobile menu and google maps or slideshow

### ISSUE THREAD

**Issue by josefzacek** [picnicss/picnic#115]
Mobile menu is hidden behind Google map or slideshow [http://owlgraphic.com/owlcarousel/index.html](http://owlgraphic.com/owlcarousel/index.html) when opened

![screen shot 2016-08-25 at 23 58 11](https://cloud.githubusercontent.com/assets/2744855/17988685/c74a275e-6b1f-11e6-9973-f7bd6228fdae.png)

**Comment by franciscop** [comment]
Should be fixed with the last release, thanks for reporting
