### ISSUE TITLE
Search box in navbar

### ISSUE THREAD

**Issue by physcocode** [picnicss/picnic#117]
Adding <input> in navbar breaks stuff ! How can I implement search box in navbar ?

**Comment by franciscop** [comment]
Please define "breaks stuff". Could you show some code sample? Could you specify it more? Please [see this article on asking technical questions](http://stackoverflow.com/help/how-to-ask)

**Comment by franciscop** [comment]
I leave this closed for now; feel free to provide more information/a small example and reopen it.
