### ISSUE TITLE
Suggestion: Plugin for other frameworks

### ISSUE THREAD

**Issue by adavie1** [picnicss/picnic#120]
Firstly, I really, really like the idea of "lightweight" CSS frameworks and thus code.

Secondly, just a random thought- (not sure how technically feasible either) how about building a plugin architecture to be able to use your invasive CSS idea for bootstrap and materialize?

By including an additional CSS file you could apply the same concept but to bootstrap or materialize to provide the L&F.

I understand this moves away from the minimalism you set out with, however, it would be a huge time saver for using those frameworks.

I imagine the grid system is neutral relative to the presentation, so in theory, that could still position any type of styled component?

**Comment by franciscop** [comment]
That'd be out of scope for this project... why don't you create a file like that and just include it in your projects? You could even pull bootstrap/materialize as a dependency and wrap it into a small library.

Yes, the grid is based on Flexbox so it should work with most/all content that you throw in.

**Comment by adavie1** [comment]
Thanks, apologies for the delayed reply.
