### ISSUE TITLE
Modal - Problem with Z-Order of Overlay

### ISSUE THREAD

**Issue by pertcode** [picnicss/picnic#124]
Hi,
I don't think modals are working correctly. I'm using latest version, 6.2.4

![modal](https://cloud.githubusercontent.com/assets/19544311/19993831/35fa2dd8-a27b-11e6-82ae-9e1304293a54.PNG)

The overlay seems to be on top of everything, including the modal window itself. I think the z-index is too high (I looked at the changes and I think the z-order was increased recently, right?).

If I change the z-index back down to 99 say, it works fine.

Please see screenshot attached. 

Thanks / Chris.

**Comment by franciscop** [comment]
Hi @pertcode that is true, I had the same problem recently but I thought it was some conflict with my code. Will fix it ASAP

**Comment by franciscop** [comment]
Should be fixed now, right?
