### ISSUE TITLE
Is it possible to include non-minimised versions of the CSS in the dist folder?

### ISSUE THREAD

**Issue by nmcgann** [picnicss/picnic#129]
For those of us non-front end devs that aren't that familiar with SCSS (or want to make a few tweaks without setting up a full build environment).

**Comment by franciscop** [comment]
Sure, if you want to do a PR you are also welcome but otherwise I'll do it, should be pretty easy. The `releases` folder is there for historic reasons, please use the `picnic.min.css` on the root.

**Comment by franciscop** [comment]
Nevermind, `picnic.css` [is already on the root](https://github.com/picnicss/picnic/blob/master/picnic.css).

**Comment by nmcgann** [comment]
Cool - that's excellent thanks.
