### ISSUE TITLE
Navigation breaks down with two menu sections on phones

### ISSUE THREAD

**Issue by ghost** [picnicss/picnic#31]
So it works great on my desktop but when using my phone I run into an issue with having two menu sections in the navigation. It just sticks out the side and fails to activate. If this is something that you are not expecting to work I can find a local work around but I figured I would report it. 

Example:
https://nullfrequency.com

**Comment by FranciscoP** [comment]
Is this problem now solved?

**Comment by franciscop** [comment]
As suggested [here](http://programmers.stackexchange.com/questions/283200), I close this issue from lack of reproduction steps and a general lack of information about the issue.
