### ISSUE TITLE
Navigation break down on safari

### ISSUE THREAD

**Issue by ChangJoo-Park** [picnicss/picnic#37]
https://dl-web.dropbox.com/get/스크린샷/스크린샷%202015-05-03%2009.40.19.png?_subject_uid=65139565&w=AAAAaw0OTZuzsXqenhoPp9l4RZi4K3RD5vvTe73N8SdRiQ

Hello, I use safari and code nav, but navigation items are not well positioned.

**Comment by Coppolaemilio** [comment]
Hello CHangJoo-Park, the dropbox image you shared is private (403), can you upload it here to github instead?

**Comment by franciscop** [comment]
I didn't have access to OS X before, but now I do. This seems to be the issue:

![screen shot 2015-05-11 at 4 15 05 pm](https://cloud.githubusercontent.com/assets/2801252/7559951/f0a61af4-f7f8-11e4-89eb-cbe6fdf8ed91.png)

**Comment by franciscop** [comment]
This comes from the same problem as [Modals are not centered in Safari](https://github.com/picnicss/picnic/issues/40), the temporary solution is [similar to this pull](https://github.com/picnicss/picnic/pull/41) and the permanent one is [deprecating the web builder](https://github.com/picnicss/picnic/issues/39).

**Comment by franciscop** [comment]
Fixed
