### ISSUE TITLE
Flat bottom buttons

### ISSUE THREAD

**Issue by olimortimer** [picnicss/picnic#38]
On your website (http://www.picnicss.com/), the five demo buttons have flat bottoms rather than rounded corners. This is being caused by `overflow: hidden` on the `render` class.

![Screenshot]
(http://s15.postimg.org/fbwnso5rf/Screen_Shot_2015_05_08_at_16_11_20.png)

This is on Chrome 42 on Mac OS X Yosemite.

**Comment by franciscop** [comment]
Oh perfect, well spotted, thank you so much. Will fix ASAP.

**Comment by franciscop** [comment]
Should be fixed by now. However, I cannot check until tomorrow
