### ISSUE TITLE
Too soon to change to the CDN

### ISSUE THREAD

**Issue by JacobEvelyn** [picnicss/picnic#42]
In the future, a little warning before a deprecation would be nice. My site just completely lost its styling with your recent CDN change.

**Comment by franciscop** [comment]
I am so sorry... I didn't realize that I made this mistake, but I did when I pushed the dev branch into heroku. I apologize, it should be fixed now.

PS, I am making the change in the following weeks, how do you think I should inform the rest of the users? I wrote a note on the main page but it is probably not enough.

**Comment by franciscop** [comment]
I am uploading the new version next Sunday 7th, is that okay?

**Comment by JacobEvelyn** [comment]
Will `<link href="//cdn.jsdelivr.net/picnicss/3.4.2/picnic.min.css" rel="stylesheet">` still be available, or will that URL change?

**Comment by franciscop** [comment]
That's the jsdelivr CDN, it should be available as long as jsdelivr exists (the project is unrelated to me)

**Comment by JacobEvelyn** [comment]
So you're saying we can use either:

- `<link href="//cdn.jsdelivr.net/picnicss/3.4.2/picnic.min.css" rel="stylesheet">` (old)
- `<link href="//cdn.jsdelivr.net/picnicss/3.4.3/picnic.min.css" rel="stylesheet">` (new)

Just making sure I understand.

**Comment by franciscop** [comment]
I am sorry but there is [no version 3.4.3 currently](https://github.com/picnicss/picnic/releases). The next version after 3.4.2 will be the 4.0, and there will not be 3.4.2 unless there's an important bug that makes me release a fix for the 3.4.3.

On the other hand, the version 3.4.2 that you pointed (first one) will always be available in that link and you can safely use it.

**Comment by JacobEvelyn** [comment]
Got it. Thanks for the clarification!
