### ISSUE TITLE
no .button.dull

### ISSUE THREAD

**Issue by NickChristensen** [picnicss/picnic#48]
There is a `dull` variant mentioned on the [button plugin docs](http://www.picnicss.com/plugins/button/), but it's getting the default blue. It's happening there on the docs, and when I try to use it.

**Comment by franciscop** [comment]
It was removed in the last version. It looked too much as the [disabled] property so I removed it. I'll update the documentation, thank you

**Comment by franciscop** [comment]
Should be fixed now
