### ISSUE TITLE
Disable hover styling on anchor in nav

### ISSUE THREAD

**Issue by ramijarrar** [picnicss/picnic#49]
The hover styling on an anchor element should be disabled within the navigation bar.

EDIT: This already seems to be the case on the picnicss site, so I assume this is code that hasn't been merged into core?

**Comment by franciscop** [comment]
I created the anchor style too fast not to delay the relase of 4.0 for too long and now I am regretting it for this same reason. You are right, it has been fixed but it still meeds merging into the master

**Comment by ramijarrar** [comment]
Okay thanks, I'll just wait for the next release
