### ISSUE TITLE
Web pages do not build out of the box

### ISSUE THREAD

**Issue by richardmitic** [picnicss/picnic#51]
The web pages (web/views/*.jade) do not build out of the box.

Using this gulp file:
```javascript
jade = require('gulp-jade');
gulp.task('html', function() { 
  gulp.src('./web/views/*.jade')
    .pipe(jade())
    .pipe(gulp.dest('./web'));
});
```
you get this error log: https://gist.github.com/richardmitic/622e082bf1f038b99598

**Comment by franciscop** [comment]
I have never built .jade files with Gulp. The referenced jade file needs some javascript variables, which are built with node. Pwrticularly,

**Comment by richardmitic** [comment]
Actually I was just trying to build the example pages, but it doesn't need to be with gulp. Is there a script to assign all the necessary variables?

**Comment by franciscop** [comment]
Yes, I am using node.js for it. Go to the root folder and type `node app.js`. Then in your browser you can see it in `localhost:3000` and navigate as normal. Is that what you are looking for?

**Comment by richardmitic** [comment]
Yes, that's perfect! Thanks for you help.
