### ISSUE TITLE
Website layout query

### ISSUE THREAD

**Issue by PAEz** [picnicss/picnic#54]
Sorry if its inappropriate to ask a general question like this, but I dont know where else to ask.

Im trying to learn or just get some css for a simple layout and I really like the way the nav stuff works (the responsive stuff) on your site and was wondering if you know of a tutorial or something that explains how it works?...Im hopeless at css.  I had a google and found a lot similar but one on this one specifically would be nice.

**Comment by franciscop** [comment]
No problem, however the nav (or maybe the modal) is probably the most complex part of Picnic and it's a mix of many small parts I've learned over the years, so if you are starting it might be a bit difficult to catch up

The main techniques I use are these (google search the bold parts for more info):

- **css media queries** for changing the style depending on the window size (responsive bits)
- **vertical centering with transformY()** for positioning the elements vertically within the nav
- **[responsive menus with css](https://css-tricks.com/responsive-menu-concepts/)**, specially point 4 is similar to what I used here

If you have any other question please feel free to ask! (:
