### ISSUE TITLE
Dropdown plugin

### ISSUE THREAD

**Issue by hadokee** [picnicss/picnic#55]
Firstly thanks you for this very impressive project. The major components are supported nicely without JavaScript backend. Maybe you only missed support for dropdown buttons/menus.

Do you think it could be implemented without javascript? Becouse I will use picnic in my project I should contribute to develop new plugins.

**Comment by franciscop** [comment]
Could you give a specific example of what you mean by dropdown? I've seen several implementations.

**Comment by hadokee** [comment]
http://getbootstrap.com/components/#btn-dropdowns

**Comment by franciscop** [comment]
I will give it a try but the markup will probably be too ugly to produce anything usable

**Comment by hadokee** [comment]
OK I understand. A valid alternative widget could be a "popover"
http://getbootstrap.com/javascript/#popovers

Do you think it could be more simple to make?

**Comment by franciscop** [comment]
Does this dropdown work for you?

> **[JSFiddle](http://jsfiddle.net/franciscop/bk9v2mq8/)**

Note: extra random letters to make sure it works in different positions

**Comment by franciscop** [comment]
You can close it by pressing anywhere outside of the dropdown. Maybe the "dropdown" name was more adequate now that I finished it and I see it (:

**Comment by hadokee** [comment]
it seems to work perfectly, great work!

**Comment by franciscop** [comment]
I won't be adding this as a plugin because the html is too complex.
