### ISSUE TITLE
Use flexbox

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#58]
https://philipwalton.github.io/solved-by-flexbox/demos/grids/

**Comment by hadokee** [comment]
+1 This is really nice feature.

**Comment by hadokee** [comment]
I'm releasing a simple css grid system with flexbox. It supports both columns and rows.
It's only an idea of  I would in picnic css as grid system. It included a simple sidebar layout too.

https://bitbucket.org/hadokee/flexgrid

**Comment by franciscop** [comment]
Hi @hadokee , unfortunately you forgot to add a License so I cannot include it in Picnic (I haven't even read it just in case). Would you mind adding the license for it, please?

Another take:

> http://gridlex.devlint.fr/

**Comment by hadokee** [comment]
Hi Francisco it was only a try. Probably gridlex is better coded and documented :)

**Comment by franciscop** [comment]
Also this one: https://github.com/IonicaBizau/gridly

**Comment by franciscop** [comment]
I [created one based on flexbox](http://codepen.io/anon/pen/LGpwmO), but I'm still not happy. There is a tradeoff to choose:

## Margins

Add a negative margin to the wrapper and a margin to the children, then do `overflow-x: hidden;` so they don't show up on the right. However this cuts box-shadow and any other thing that people using the library might have.

The advantage is that then the client-code is really clean (unless you want to change the gutter) so it's flexible and intuitive. This is really similar implementation to the one currently with Picnic. Example for client code:

```scss
.grid > *:first-child {
  width: 100%;
}
```

## Space between

Using flexbox and `justify-content: space-between;` we can get pretty close. However, this yields a nightmare of numbers to maintain (for the developer using picnic) like `max-width: calc(50% - #{$gutter/2});`.

Then when there's a N number of hanging items, where N > 1 and N < columns, the space is gotten in the middle also, which is really odd. See issue (or [google](https://www.google.es/search?q=flexbox+last+row)). So the solution is even uglier:

```scss
.grid.three > *:last-child:nth-child(3n+2) {
  margin-right: calc(33.3333% + #{$gutter/4});
  //max-width: calc(100% * 2 / 3 - #{$gutter/3});
}
```

I am not sure if using flexbox and re-implementing the whole grid system is worth it here. Maybe witha light implementation of [Solved with Flexbox](https://github.com/philipwalton/solved-by-flexbox) is enough, since the state of the technology is not there yet (see next point).

## Future

In the far, far away future this might be interesting (right now not even firefox/chrome support it). I hope this time they get it right:

https://css-tricks.com/almanac/properties/c/columns/

**Comment by franciscop** [comment]
No flexbox, I'll switch it also to floats since they are much more flexible than table
