### ISSUE TITLE
Website migration to Github Pages

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#62]
The website now runs on Heroku with Node.js, ideally it should be hosted on Github Pages for these reasons:

- It's free (vs ~84$/year on Heroku right now). While it's not too much, I have few projects and I'm migrating them
- The codebase is messy. I think it's overly complex right now for something really simple.
- Switch to grunt. Again, I'm switching a number of project to grunt, so just doing `grunt watch` builds the website nicely. This makes it a lot easier to develop, deleting the grunt work of editing many files manually each time there's a new release.
- The menu is confusing since many people click on "Documentation" instead of Plugins. Plugins refer to Plugins Documentation, and since Picnic is completely made out of plugins, this is the file most of the people probably want (which is not intuitive on first load).

For these reasons, I think it's better to switch to Github pages. I have already a Gruntfile to do something similar so it should be relatively easy.

**Comment by franciscop** [comment]
In the migration also there will be only one file:

> picnic.css

All of the files inside `plugins.css` will be merged into `picnic.css`. This grants a major release, but should not break things since `src/picnic` is kept in the same folder

**Comment by philippnagel** [comment]
Perhaps Plugins should be renamed to e.g. Components or Elements?

**Comment by franciscop** [comment]
I like both *Components* and *Elements* more than *plugins*, thanks for the suggestions

**Comment by franciscop** [comment]
I have had few problems with using Picnic in the way it is now, mainly small bugs that are easy to fix but cannot do it to avoid duplicating the code everywhere. So I need to accelerate and close this issue ASAP.

**Comment by franciscop** [comment]
Migrated
