### ISSUE TITLE
Sliding responsive menu not working

### ISSUE THREAD

**Issue by rohan-deshpande** [picnicss/picnic#63]
Heya, I'm building a JavaScript library and chose to use Picnic for the styling of my examples page. Quite clean and nice!

One thing though, the slide out for the mobile nav is not working for me. My nav component collapses to its `menu` button mode at the correct breakpoints, but pressing it does nothing. Here's my markup

    <nav class='demo'>
        <a href="index.html" class='brand'>Demos</a>
        <input id="bmenub" type="checkbox" class="show">
        <label for="bmenub" class="burger pseudo button toggle">menu</label>
        <div class='menu'>
            <a class='button' href="intro.html">
                Intro
            </a>
            <a class='button' href="local.html">
                Local
            </a>
            <a class='button' href="remote.html">
                Remote
            </a>
        </div>
    </nav>

FYI I'm using Chrome and I'm getting the library and plugins from the CDN.

**Comment by franciscop** [comment]
Thank you for trying Picnic. Note that "plugins" also include the core plugins, so you should only include one of them (in this case, *plugins*). Could you share more info, please? [In this jsfiddle](https://jsfiddle.net/franciscop/wcwbzhkx/) it seems it's working fine, right?

**Comment by rohan-deshpande** [comment]
Hmm it seems to be working now. I'm not exactly sure what was happening before. If I see this again I will make a note of what I did and see if I can replicate it. Weird! Thanks for replying feel free to mark this as closed.

**Comment by franciscop** [comment]
Awesome, if you find anything else please update the issue. I'm closing this for now (:
