### ISSUE TITLE
add background color to inputs

### ISSUE THREAD

**Issue by choma** [picnicss/picnic#64]
Some browsers adds own styles to inputs. This is how inputs looks in Firefox 46.0a2 dev edition (under Debian 8, Gnome 3 with Adawaita Dark theme):

![screen shot 2016-01-31 at 18 15 04](https://cloud.githubusercontent.com/assets/4775453/12705044/76dad082-c847-11e5-98ff-dbe5d09e3e09.png)

Note that placeholders and input content are invisible.

**Comment by franciscop** [comment]
Wow that sucks, I'll fix it as soon as possible, thanks for reporting it!

**Comment by franciscop** [comment]
[Done](https://github.com/picnicss/picnic/blob/master/src/plugins/input/_class.scss), thank you for the report:

```scss
$picnic-input-background: #fff !default;
```

```scss
background: $picnic-input-background;
```
