### ISSUE TITLE
Nested tabs

### ISSUE THREAD

**Issue by katyo** [picnicss/picnic#66]
I tried to make nested tabs and I have a problem.

I have three tabs on top level, four tabs into contents of second tab and two tabs into contents of third tab.
Three tabs at top level and four tabs at second tab works perfect.
But I have a trouble with two tabs at third tab: the content into row shifted right for width of row.
As I see the *css* of top level tabs have effect to nested tabs.

I'm yet newbie in **picnic**, but I think there is the elegant way to solve this issue.
Thanks.

**Comment by franciscop** [comment]
It's awesome that you could fix it, thank you so much!
