### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by wesleywesley** [picnicss/picnic#69]
What is the browser support for this?

**Comment by franciscop** [comment]
That's relative as this is a one-person project mainly. It's tested from time to time in IE11, but bug fixes are accepted down to IE9 as explained in the [Browser Support IE9+ section](https://github.com/picnicss/picnic#browser-support-ie9).

However I'm thinking of bumping it to IE11 so [we can use flexbox](http://caniuse.com/#feat=flexbox). Also note that there are no extensive tests in place, so by *testing* I mean "going to the page, clicking a bunch of things and see if it works".
