### ISSUE TITLE
Modal: blurry font ie11

### ISSUE THREAD

**Issue by hroma** [picnicss/picnic#77]
![modal-blurry-font-ie](https://cloud.githubusercontent.com/assets/8946523/13372176/c0f0014e-dd3a-11e5-8f12-3900a86980f7.gif)

[Pure CSS Modal without blurry effect (drublic css modal)](http://drublic.github.io/css-modal/)

**Comment by hroma** [comment]
After some investigation, issue come from `translateX(-50%) translateY(-50%)` returning non-integer value. Resolution would require javascript fix. For more information check [this](http://keithclark.co.uk/articles/gpu-text-rendering-in-webkit/).
For pure css modal inspiration (without issue) check this [drublic css modal](http://drublic.github.io/css-modal/#!)

**Comment by franciscop** [comment]
The `translateX` and `translateY` are there because that's about the best way to vertically center a div and unfortunately there's not a good enough solution. Drublic CSS Modal is not centered vertically so it's a different implementation.

Does this answer fix it for you?

> [Blurry text in Internet Explorer](http://stackoverflow.com/a/31883042/938236)

**Comment by hroma** [comment]
Sorry, but the "Blurry text in Internet Explorer" answer doesn't fix my issue. I've implemented a **javascript workaround** to vertically/horizontally center the modal. It's currently the only option I've found to avoid the blurry effect in IE.

**Comment by franciscop** [comment]
Have you implemented it just complementing Picnic CSS with some js? or did you have to remove some CSS? If the former, then I could publish it as a recommendation. IE seems to be going down quite fast so in 6-12 months this shouldn't really be an issue anymore. Also it doesn't seem too big of an issue, more like an annoyance (which would be fixed if in Chrome/Firefox/Safari/Edge/Android). So I'm all in about explaining and showing a possible solution, but not about requiring js for Picnic to work.
