### ISSUE TITLE
Adding a Reset SCSS

### ISSUE THREAD

**Issue by akram-rameez** [picnicss/picnic#78]
Adding a reset scss could somehow help in integration of picnic on existing projects. Low Priority feature request

**Comment by franciscop** [comment]
Hi @akram-rameez, what would be the benefits of this and how is it different from the current reset? Do you mean [like this one](https://gist.github.com/hcatlin/1027867)?

**Comment by akram-rameez** [comment]
I'm sorry, but I couldn't find an existing reset. But I am talking about the reset css you showed.

**Comment by franciscop** [comment]
Then *there is* already one, it's called Normalize and it's included in [src/plugins/normalize](https://github.com/picnicss/picnic/tree/master/src/plugins/normalize).
