### ISSUE TITLE
Checkbox in iOS

### ISSUE THREAD

**Issue by franciscop** [picnicss/picnic#79]
From Hacker News:

> When going to http://picnicss.com/documentation#checkbox on an iPhone (iOS 9.2.1), the checkmark doesn't hide when it's unchecked; it just gets bigger. So on your example, the default selected boxes just look like they have big checkmarks in them. Sorry I don't have the time to write an issue at the moment.

**Comment by coppolaemilio** [comment]
![screen shot 2016-02-29 at 8 01 08 pm](https://cloud.githubusercontent.com/assets/2206700/13405532/36125d74-df1f-11e5-8d7d-c28d3996ea25.png)

I can try to fix this one when I have some free time.
