### ISSUE TITLE
Splitting Nav into Left - Center - Right blocks

### ISSUE THREAD

**Issue by hroma** [picnicss/picnic#80]
Is it possible to create a menu with different stacks positions ? [example of what i mean](http://www.bootply.com/3iSOTAyumP)
Any help would be much appreciated. Thanks.

I've already tried this (breaks everything):

```html
<style>
    .left {
        position: absolute;
        top: 0px;
        left: 180px;
        text-align: left;
     }
    .right {
        position: absolute;
        top: 0px;
        right: 0px;
       }
</style>
<nav class="user-menu">
    <div class="brand">
        <a href="/"><img class="logo" src="/images/logo.png"/></a> <span></span>
    </div>
    <input id="bmenub" type="checkbox" class="show"> <label for="bmenub" class="burger pseudo button">Menu</label>
    <div class="menu">
        <div class="left">
            <a class="button pseudo" href="#">Link1</a>
            <a href="#">Link2</a></div>
        <div class="right">
            <a href="#">Link3</a>
            <a href="#">Link4</a>
        </div>
    </div>
</nav>
```

**Comment by franciscop** [comment]
Right now the `.brand` is the *left* menu and the `.menu` is the *right* one. However the left menu won't become responsive, it will just stay as is. Unfortunately the bootply you sent just breaks (doesn't work) on mobile view, so I'm not sure of the expected result.

Having a `.left` and `.right` menu inside the `.menu` right now is a hell waiting to happen. If you really need it, you could just reuse the `<nav>` and then make the inner elements by yourself.
