### ISSUE TITLE
Open to changing directory structure?

### ISSUE THREAD

**Issue by jrhorn424** [picnicss/picnic#84]
Hi! I was wondering if you'd be open to PR changing the directory structure to something more in line with, say, the way [Foundation organizes its imports](https://github.com/zurb/foundation-sites/blob/develop/scss/foundation.scss)?

Trying to use Picnic (Sass) with Ember has proven [painful](https://github.com/aexmachina/ember-cli-sass/issues/111). Using a release is painless.

**Comment by franciscop** [comment]
Which one do you want exactly?

- Making `picnic.scss` being in the root
- Making all imported source files as *descendants* of the folder where `picnic.scss` is stored (similar to [Umbrella JS](https://github.com/umbrellajs/umbrella))

If the first one is implemented, then the second one also happens, but not the other way around. I'm all in with the second one, but if you want the first one please let me consider it.

**Comment by jrhorn424** [comment]
@franciscop I was asking mostly for the second option.

**Comment by franciscop** [comment]
It should be fixed now, right? Does this make any problem?

```scss
@import '../bower_components/compass-breakpoint/stylesheets/breakpoint';
```

**Comment by franciscop** [comment]
Fixed the bower components also and bumped it to 5.2, it should work now :smile:

**Comment by jrhorn424** [comment]
Awesome! Much appreciated.
