### ISSUE TITLE
Tooltip documentation?

### ISSUE THREAD

**Issue by aqtrans** [picnicss/picnic#85]
First off, fantastic work! 
I love the simplicity of this "framework". :smile: My HTML is so clean and pretty now. 

This is not really a bug, but I noticed that there is a tooltip plugin, which seems to be included in the minified copy available here, but it seems to be missing from the current documentation page. 
Is this intended, like a feature not ready for production?

**Comment by franciscop** [comment]
Totalolly agree, I made a mistake and forgot to change `src/plugins/tooltip/documentation.md` into `src/plugins/tooltip/readme.md` so it's not picked up by the new build system.
