### ISSUE TITLE
Project showcase

### ISSUE THREAD

**Issue by kunagpal** [picnicss/picnic#89]
A project showcase section can (and probably should) be included, as has already been done for various major front end frameworks like Bootstrap, Foundation, UIKit and others.

**Comment by dyu** [comment]
Checkout http://picnicss.com/tests if you haven't already.

**Comment by kunagpal** [comment]
That is essentially documentation. I was talking more in line with something like the samples provided here:

* http://getuikit.com/showcase/
* http://expo.getbootstrap.com/
* http://foundation.zurb.com/learn/brands.html

**Comment by franciscop** [comment]
This is a really good idea, however I don't know many people who have worked with Picnic so far. Do you have any project to showcase?

I could add:

- http://umbrellajs.com/
- http://makersupv.com/

Which are functional websites. Doing a showcase itself and creating each of the sites individually would consume way too much time for me.

**Comment by kunagpal** [comment]
Both of the above sites look just fine, a separate showcase page can and should be added for them. Putting a shout out for showcase candidates on the Picnic CSS site would also attract attention.

**Comment by franciscop** [comment]
That's a great idea, I'll get it done some time this week

**Comment by franciscop** [comment]
Small showcase done in the homepage. Maybe an image would have been better, but I think it's pretty cool to have an interactive iframe within the page itself.

For faster loads, it doesn't start loading the two iframes until the browser starts to scroll (or reloads scrolled).

If anyone wants to add another website just drop a link somewhere and I'll add it.
