### ISSUE TITLE
Nav  vertical-align on Android

### ISSUE THREAD

**Issue by br-lemes** [picnicss/picnic#92]
My Android 4.4.2 webkit based browser (https://github.com/anthonycr/Lightning-Browser) render wrong vertical-align nav. I added the following to my custom CSS to solve:

```
nav .brand, nav .burger { -webkit-transform: translateY(-50%); }
```

But NOT touch nav .menu or it's contents will get blank.

**Comment by franciscop** [comment]
Do you mean if you touch `.menu` it just dissapears? Some people is having the same issue, I'll dig into it, thanks for reporting it.

I'll also add the `-webkit-` prefix

**Comment by br-lemes** [comment]
No. I have no issue about `.menu` in current version. I mean prefix just the classes `.brand` and `.burger.` If you add:

```
nav .menu { -webkit-transform: translateY(-50%); }
```

Then menu disappears.

I thought to fork and pull request, but I'm not very good in CSS. I get puzzled because in your code the classes `.brand,` `.menu,` `.burger` have the transform all together but prefixing then all at once breaks. I don't know exactly why. I also don't know if I have to change `_class.scss` or `_plugin.scss` (apparently both have the same code) and decided to leave unchanged and overwrite with my own custom css afterwards.

By the way, my updated Chrome (webkit) desktop browser resized window doesn't have any issue at first, and the menu doesn't disappears even if prefixing the class `.menu` also.

**Comment by franciscop** [comment]
The code is kind of messy , but the effort/benefit to clean up everything is too high right now. I'd need few days that I prefer to use to [create new projects](umbrellajs.com/) or improve Picnic itself (testing [this ATM](http://francisco.io/flexpoint/)).

However I'll always try to fix all bugs, and clean up the code while doing so. So I'll dig into it, the two issues mentioned might be related :)

**Comment by br-lemes** [comment]
I didn't mean your code is messy. Your code is awesome. I'm migrating from Bootstrap.

I said I don't understand CSS very well, and get caught by my own deficient understanding (maybe I also can't write English clearly).

**Comment by franciscop** [comment]
Could you show some image and possibly a jsfiddle, please? I am sorry but I keep not understanding the issue here.

1. Is there any problem by default in the stated browser?

1. When does this problem happen?

1. What us the problem? How should it look vs how does it look? Screenshots/demo if possible please.

1. Do you know any workaround or fix? If so, can you show it, please?

**Comment by br-lemes** [comment]
This is the problem on Android 4.4.2 stock browser or any other based on webview component:
![android](https://cloud.githubusercontent.com/assets/1540777/16462541/bbf1b77a-3dff-11e6-8331-2e15b22dc59c.png)

This is how it should look (Firefox adaptive design to screenshot):
![firefox](https://cloud.githubusercontent.com/assets/1540777/16462545/be8f1fb8-3dff-11e6-8b1d-50de9b329e70.png)

This fix the problem:

`nav .brand, nav .burger { -webkit-transform: translateY(-50%); }`

The `-webkit-` prefix should be applied to `nav .brand` and `nav .burger` but not to `nav .menu`.

**Comment by franciscop** [comment]
Why not to nav .menu? It is that way so it is vertically centered. Realize that later it is nulled in responsive mode.
