### ISSUE TITLE
[Tab]Previous tab content not hidden when switch to other

### ISSUE THREAD

**Issue by codehz** [picnicss/picnic#96]
Screenshot
![image](https://cloud.githubusercontent.com/assets/13158903/15863076/401bbf94-2d04-11e6-981f-ecb41ef58a5d.png)
(Test in Chrome Version 53.0.2756.0 dev-m (64-bit))
(and os is Windows 10)

it seem like width calculation error...

**Comment by franciscop** [comment]
Thanks for reporting it, it is probably due to the change from `.row` to `.flex`, that I totally forgot that `.tabs` inherited from `.row` and it's quite messy now. Also [reported on Hacker News](https://news.ycombinator.com/item?id=11854016)

**Comment by franciscop** [comment]
The problem was only on the test; the tab works as expected
