### ISSUE TITLE
working with font-awesome

### ISSUE THREAD

**Issue by arisAlexis** [picnicss/picnic#98]
Any hints on how to use this? I want to avoid fontella because I am not serving static content and using webpack which messes things a bit (unless you have a solution?).

When I am using fontawsome the css of the button is changed for example the height.

**Comment by franciscop** [comment]
Can you show me an example in a jsfiddle, please?

**Comment by arisAlexis** [comment]
sure https://jsfiddle.net/hgqyt5sc/4/

**Comment by franciscop** [comment]
There you go :smile: 

> https://jsfiddle.net/franciscop/hgqyt5sc/5/

I will add it by default

**Comment by arisAlexis** [comment]
thanks! works now
