### ISSUE TITLE
new npm version

### ISSUE THREAD

**Issue by arisAlexis** [picnicss/picnic#99]
pulling the npm version gives you the old grid system with row and breaks everything if you change from a CDN based

**Comment by gargrave** [comment]
Yeah, it took me a while to figure why I couldn't get anything working properly with the npm version. Looks like it is still on 4.1.2:
https://www.npmjs.com/package/picnic

Are there any plans to update the npm version? If not, it might be wise to just kill it altogether and tell users to stick with Bower or CDN or whatever.

**Comment by franciscop** [comment]
I thought it was updated automatically for some reason...I'll investigate this weekend, sorry for this

**Comment by franciscop** [comment]
Related: http://stackoverflow.com/questions/13507763/do-i-need-to-publish-to-npm-every-time-i-update-a-package-available-via-git

**Comment by gargrave** [comment]
@franciscop
No worries! It's easy enough to just use the Bower version instead--I just usually go for npm first, and I was thrown off for longer than I care to admit before I noticed the versioning discrepancy. :)

**Comment by arisAlexis** [comment]
Although I haven't done npm publishing I really think it's worth it, bower is losing in popularity and people just use npm for everything.

**Comment by franciscop** [comment]
The version 6.1.1 should be published now. Totally agree about npm > bower, however bower auto updates while npm has to be `npm publish`ed
